export const KEYWORDS = [
  "DEVS",
  "developers",
  "programming",
  "coding",
  "web development",
  "software engineering",
  "tech blog",
  "developer community",
  "stories",
  "knowledge",
  "tutorials",
  "guides",
  "tips",
  "best practices",
  "career",
  "freelance",
  "hire developers",
];
