// types hoặc constants file

import {
  Cpu,
  Code,
  Palette,
  Briefcase,
  TrendingUp,
  DollarSign,
  Heart,
  GraduationCap,
  Microscope,
  BookOpen,
  Paintbrush,
  Trophy,
  Music,
  Camera,
  Plane,
  UtensilsCrossed,
  Dumbbell,
  Shirt,
  Gamepad2,
  Sparkles,
  Hammer,
  Car,
  Home,
  Scale,
  Leaf,
  Landmark,
  Brain,
  Lightbulb,
  BookMarked,
  Languages,
  Calculator,
  Atom,
  FlaskConical,
  Dna,
  Telescope,
  Building2,
  Cog,
  Wheat,
  PawPrint,
  Film,
} from "lucide-react";
import { LucideIcon } from "lucide-react";
export interface ListCategory {
  id: number;
  title: string;
  icon?: LucideIcon; // Thêm icon nếu cần
}

export const listCategory: ListCategory[] = [
  { id: 1, title: "Technology", icon: Cpu },
  { id: 2, title: "Programming", icon: Code },
  { id: 3, title: "Design", icon: Palette },
  { id: 4, title: "Business", icon: Briefcase },
  { id: 5, title: "Marketing", icon: TrendingUp },
  { id: 6, title: "Finance", icon: DollarSign },
  { id: 7, title: "Health", icon: Heart },
  { id: 8, title: "Education", icon: GraduationCap },
  { id: 9, title: "Science", icon: Microscope },
  { id: 10, title: "History", icon: BookOpen },
  { id: 11, title: "Art", icon: Paintbrush },
  { id: 12, title: "Sports", icon: Trophy },
  { id: 13, title: "Music", icon: Music },
  { id: 14, title: "Photography", icon: Camera },
  { id: 15, title: "Travel", icon: Plane },
  { id: 16, title: "Food & Cooking", icon: UtensilsCrossed },
  { id: 17, title: "Fitness", icon: Dumbbell },
  { id: 18, title: "Fashion", icon: Shirt },
  { id: 19, title: "Gaming", icon: Gamepad2 },
  { id: 20, title: "Lifestyle", icon: Sparkles },
  { id: 21, title: "DIY & Crafts", icon: Hammer },
  { id: 22, title: "Automotive", icon: Car },
  { id: 23, title: "Real Estate", icon: Home },
  { id: 24, title: "Legal", icon: Scale },
  { id: 25, title: "Environment", icon: Leaf },
  { id: 26, title: "Politics", icon: Landmark },
  { id: 27, title: "Psychology", icon: Brain },
  { id: 28, title: "Philosophy", icon: Lightbulb },
  { id: 29, title: "Literature", icon: BookMarked },
  { id: 30, title: "Languages", icon: Languages },
  { id: 31, title: "Mathematics", icon: Calculator },
  { id: 32, title: "Physics", icon: Atom },
  { id: 33, title: "Chemistry", icon: FlaskConical },
  { id: 34, title: "Biology", icon: Dna },
  { id: 35, title: "Astronomy", icon: Telescope },
  { id: 36, title: "Architecture", icon: Building2 },
  { id: 37, title: "Engineering", icon: Cog },
  { id: 38, title: "Agriculture", icon: Wheat },
  { id: 39, title: "Pets & Animals", icon: PawPrint },
  { id: 40, title: "Entertainment", icon: Film },
];
